Rise-Vision/rv-common-e2e

- lib/common/helper.js
@alex-deaconu please review. cheers
> Fixed waitDisappear

- lib/pages/commonHeaderPage.js
- lib/pages/googleAuthPage.js
@alex-deaconu I have to change it as the e2e tests for schedules were constantly failing. Please review.
cheers
> Fixed submit-approve

- lib/pages/googleAuthPage.js
@alex-deaconu I added steps to pass through the google verification. Please review.
@ezequielc FYI.
cheers
> Added steps for the google's it is me verification

- lib/common/helper.js
@alex-deaconu @ezequielc please review. cheers
> Added helper function to wait for an element text to change

- lib/common/helper.js
Waiting for an alert confirmation to appear. Needed for CH tests.
@rodrigopavezi please review. Thanks.
> Wait for an alert to appear

- lib/pages/commonHeaderPage.js
- lib/pages/googleAuthPage.js
Used by the CH to log in to a different user for the registration scenarios.
@rodrigopavezi please review. Thanks.
> Add the ability to provide signin credentials

- lib/pages/commonHeaderPage.js
@alex-deaconu  @rodrigopavezi Please review. Thanks
> Added Sign out function

- lib/pages/commonHeaderPage.js
Add signOutOfGoogle button (for future use)
Wait for spinner before signing out (required for CH)
@rodrigopavezi @ezequielc a quick improvement on the PR from yesterday so I can use the elements in the CH. Please review. Thanks.
> Add getters for signout elements

- lib/common/helper.js
- lib/pages/commonHeaderPage.js
- lib/pages/googleAuthPage.js
- package.json
popup authentication process.
@ezequielc please review. cheers
> Changed google auth scripts to handle the new

- lib/common/helper.js
- lib/pages/commonHeaderPage.js
- lib/pages/googleAuthPage.js
- package.json
Changed google signin script to first check for
account chooser first with a lower timeout
Fixed waiting for load spinner to disappear after login
@ezequielc please review. cheers
> Added a timeout parameter for the helper functions

- lib/common/helper.js
- lib/pages/commonHeaderPage.js
- lib/pages/googleAuthPage.js
- package.json
Reverts Rise-Vision/rv-common-e2e#16
@ezequielc I need to revert this before I can revert https://github.com/Rise-Vision/rv-common-e2e/pull/15. Please review. Thanks.
> Revert "Added a timeout parameter for the helper functions"

- lib/common/helper.js
- lib/pages/commonHeaderPage.js
- lib/pages/googleAuthPage.js
- package.json
Reverts Rise-Vision/rv-common-e2e#15
This gets us back to pre-auth2 version.
@ezequielc please review. Thanks.
> Revert "Changed google auth scripts to handle the new"

- lib/pages/googleAuthPage.js
- package.json
Build is finally fixed with this branch: https://circleci.com/gh/Rise-Vision/editor-app/884
@ezequielc please review. Thanks!
> Update id for Account chooser

- lib/pages/commonHeaderPage.js
- package.json
CH Sign In button may not be available after sign out as in Apps login page.
@alex-deaconu Please review. Thanks!
> Check signout modal disappear

- lib/pages/googleAuthPage.js
- package.json
Updated id's and use text to search for elements
> Fix google authentication location check

- lib/pages/commonHeaderPage.js
@alex-deaconu Please review. Thanks
> Added functions to CH helper to manage sub companies

- lib/common/helper.js
@fjvallarino @ezequielc  please review
> Fix encoding and redirect compare output from stderr

- lib/common/helper.js
- package.json
@fjvallarino @ezequielc please review
> Remove resizing and log comparison to stdout

- lib/common/helper.js
@settinghead @rodrigopavezi please review
@Rise-Vision/delivery @Rise-Vision/apps FYI
> Add google signin handler

- lib/common/helper.js
- package.json
Hopefully this avoids conflicts when an additional popup is displayed.
Occasionally a customer feedback popup will appear in front of the
submit button.
@settinghead @donnapep please review
> Use enter rather than trying to click

- lib/pages/googleAuthPageNew.js
@fjvallarino Please review. Thanks
> Fix city challenge
